import { useState } from 'react';
import { Alert, Button, MenuItem, Paper, Select, Snackbar, Switch, TextField } from '@mui/material';
import { LocalOfferOutlined, SaveOutlined, RestartAlt } from '@mui/icons-material';
import { settingsMockService } from './services/settingsMockService';
import './settings.css';

const SwitchRow = ({ label, help, checked, onChange, disabled = false }) => <div className="settings-switch-row"><div><strong>{label}</strong><small>{help}</small></div><Switch checked={checked} onChange={(event) => onChange(event.target.checked)} disabled={disabled} inputProps={{ 'aria-label': label }} /></div>;
const numberError = (value, type) => !Number.isFinite(Number(value)) || Number(value) <= 0 || (type === 'Percentage' && Number(value) > 100);

export function DiscountConfiguration() {
  const original = settingsMockService.getDiscountConfiguration();
  const [config, setConfig] = useState(original); const [saved, setSaved] = useState(original); const [toast, setToast] = useState(''); const [previewReason, setPreviewReason] = useState(''); const [discountPreview, setDiscountPreview] = useState('');
  const dirty = JSON.stringify(config) !== JSON.stringify(saved);
  const maxInvalid = numberError(config.maximumValue, config.maximumType);
  const previewInvalid = config.requireOverrideReason && config.allowManualOverride && previewReason.length > 0 && previewReason.trim().length < Number(config.minimumReasonLength);
  const discountPreviewInvalid = config.enforceMaximum && discountPreview !== '' && Number(discountPreview) > Number(config.maximumValue);
  const update = (key, value) => setConfig((current) => ({ ...current, [key]: value }));
  const updateRole = (id, key, value) => setConfig((current) => ({ ...current, roles: current.roles.map((role) => role.id === id ? { ...role, [key]: value } : role) }));
  const save = () => { if (maxInvalid || config.roles.some((role) => role.canApply && (Number(role.maximum) < 0 || Number(role.maximum) > 100))) return; const next = settingsMockService.saveDiscountConfiguration(config); setConfig(next); setSaved(next); setToast('Discount configuration saved.'); };
  return <main className="settings-page"><header className="settings-page-header"><div><p className="settings-eyebrow">Settings / Administration</p><h1>Discount Configuration</h1><p>Control discount limits and who can apply or override them.</p></div><div className="settings-actions"><Button variant="outlined" startIcon={<RestartAlt />} disabled={!dirty} onClick={() => setConfig(saved)}>Reset</Button><Button variant="contained" startIcon={<SaveOutlined />} disabled={!dirty || maxInvalid} onClick={save}>Save Changes</Button></div></header>
    <section className="settings-layout"><Paper className="settings-panel" elevation={0}><div className="settings-panel-heading"><LocalOfferOutlined /><div><h2>Maximum Discount Rules</h2><p>The organization-wide cap for discounts entered by billing users.</p></div></div><div className="settings-form-grid"><TextField select label="Maximum Discount Type" value={config.maximumType} onChange={(e) => update('maximumType', e.target.value)}><MenuItem value="Percentage">Percentage</MenuItem><MenuItem value="Fixed Amount">Fixed Amount</MenuItem></TextField><TextField label={`Maximum Discount Value${config.maximumType === 'Percentage' ? ' (%)' : ' (₹)'}`} type="number" value={config.maximumValue} onChange={(e) => update('maximumValue', e.target.value)} error={maxInvalid} helperText={maxInvalid ? (config.maximumType === 'Percentage' ? 'Enter a value greater than 0 and no more than 100.' : 'Enter a value greater than 0.') : `Configured maximum: ${config.maximumType === 'Percentage' ? `${config.maximumValue}%` : `₹${config.maximumValue}`}`} inputProps={{ min: 0, max: config.maximumType === 'Percentage' ? 100 : undefined, step: 'any' }} /><div className="settings-select-field"><label htmlFor="discount-status">Configuration status</label><Select id="discount-status" value={config.status} onChange={(e) => update('status', e.target.value)}><MenuItem value="Active">Active</MenuItem><MenuItem value="Inactive">Inactive</MenuItem></Select></div></div></Paper>
    <Paper className="settings-panel" elevation={0}><div className="settings-panel-heading"><div><h2>Discount Rule Controls</h2><p>Choose which discount methods are available while creating an invoice.</p></div></div><div className="settings-form-grid"><div className="settings-select-field"><label htmlFor="discount-type">Discount type</label><Select id="discount-type" value={config.discountType} onChange={(e) => update('discountType', e.target.value)}><MenuItem value="Fixed">Fixed</MenuItem><MenuItem value="Percentage">Percentage</MenuItem></Select></div><div className="settings-select-field"><label htmlFor="application-level">Default application level</label><Select id="application-level" value={config.applicationLevel} onChange={(e) => update('applicationLevel', e.target.value)}><MenuItem value="Line Level">Line Level</MenuItem><MenuItem value="Invoice Level">Invoice Level</MenuItem></Select></div></div><div className="settings-switch-list"><SwitchRow label="Allow line-level discount" help="Lets users discount an individual invoice item." checked={config.allowLineLevel} onChange={(value) => update('allowLineLevel', value)} /><SwitchRow label="Allow invoice-level discount" help="Lets users discount the total invoice." checked={config.allowInvoiceLevel} onChange={(value) => update('allowInvoiceLevel', value)} /><SwitchRow label="Enforce maximum discount" help="Blocks values that exceed the configured organization maximum." checked={config.enforceMaximum} onChange={(value) => update('enforceMaximum', value)} /></div>{config.enforceMaximum && <><Alert severity="info" className="settings-inline-alert">Values above {config.maximumType === 'Percentage' ? `${config.maximumValue}%` : `₹${config.maximumValue}`} will show a validation message during billing.</Alert><TextField className="settings-preview-input" label={`Discount validation preview (${config.maximumType === 'Percentage' ? '%' : '₹'})`} type="number" value={discountPreview} onChange={(e) => setDiscountPreview(e.target.value)} error={discountPreviewInvalid} helperText={discountPreviewInvalid ? `Discount cannot exceed the configured maximum of ${config.maximumType === 'Percentage' ? `${config.maximumValue}%` : `₹${config.maximumValue}`}.` : 'Try a value to preview maximum-discount enforcement.'} inputProps={{ min: 0, step: 'any' }} /></>}</Paper>
    <Paper className="settings-panel settings-full" elevation={0}><div className="settings-panel-heading"><div><h2>Role Permissions</h2><p>Mock role rules for frontend development. Save updates to the local mock state.</p></div></div><div className="settings-table-wrap"><table className="settings-table"><thead><tr><th>Role</th><th>Can Apply Discount</th><th>Maximum Allowed (%)</th><th>Can Override Maximum</th><th>Requires Override Reason</th><th>Status</th></tr></thead><tbody>{config.roles.map((role) => <tr key={role.id}><td><strong>{role.role}</strong></td><td><Switch checked={role.canApply} onChange={(e) => updateRole(role.id, 'canApply', e.target.checked)} inputProps={{ 'aria-label': `${role.role} can apply discount` }} /></td><td><TextField size="small" type="number" value={role.maximum} disabled={!role.canApply} error={role.canApply && (Number(role.maximum) < 0 || Number(role.maximum) > 100)} onChange={(e) => updateRole(role.id, 'maximum', e.target.value)} inputProps={{ min: 0, max: 100 }} /></td><td><Switch checked={role.canOverride} disabled={!role.canApply} onChange={(e) => updateRole(role.id, 'canOverride', e.target.checked)} inputProps={{ 'aria-label': `${role.role} can override maximum` }} /></td><td><Switch checked={role.requiresReason} disabled={!role.canApply || !role.canOverride} onChange={(e) => updateRole(role.id, 'requiresReason', e.target.checked)} inputProps={{ 'aria-label': `${role.role} requires reason` }} /></td><td><span className={`settings-status ${role.status === 'Active' ? 'active' : 'inactive'}`}>{role.status}</span></td></tr>)}</tbody></table></div></Paper>
    <Paper className="settings-panel settings-full" elevation={0}><div className="settings-panel-heading"><div><h2>Manual Discount Rules / Overrides</h2><p>Define the safeguards used when an authorized user exceeds the usual limit.</p></div></div><div className="settings-switch-list"><SwitchRow label="Allow manual override" help="Lets permitted roles exceed the configured maximum." checked={config.allowManualOverride} onChange={(value) => update('allowManualOverride', value)} /><SwitchRow label="Require override reason" help="Records a reason whenever an override is used." checked={config.requireOverrideReason} disabled={!config.allowManualOverride} onChange={(value) => update('requireOverrideReason', value)} /></div>{config.allowManualOverride && <div className="settings-form-grid settings-preview"><TextField label="Minimum reason length" type="number" value={config.minimumReasonLength} disabled={!config.requireOverrideReason} onChange={(e) => update('minimumReasonLength', e.target.value)} inputProps={{ min: 1 }} /><TextField label="Override Reason (preview)" placeholder="Enter reason for exceeding configured discount limit" value={previewReason} onChange={(e) => setPreviewReason(e.target.value)} disabled={!config.requireOverrideReason} error={previewInvalid} helperText={previewInvalid ? `Reason must be at least ${config.minimumReasonLength} characters.` : config.requireOverrideReason ? `At least ${config.minimumReasonLength} characters required.` : ''} /></div>}</Paper></section><Snackbar open={Boolean(toast)} autoHideDuration={3000} onClose={() => setToast('')} message={toast} /></main>;
}
